apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
type: Opaque
data:
  db-name: {{ .Values.backend.dbName | b64enc | quote }}
  db-user: {{ .Values.backend.dbUser | b64enc | quote }}
  db-pass: {{ .Values.backend.dbPass | b64enc | quote }}