backend:
  secretName: db-secret
  dbName: strapi
  dbUser: strapi
  dbPass: strapi

postgresql:
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: strapi
    password: strapi
    database: strapi